const images = {
  tradebridge: require("./Assets/tradebridge.svg").default,
  arrowprocess: require("./Assets/arrowprocess.png").default,
  backbutton: require("./Assets/backbutton.svg").default,
  close: require("./Assets/close.svg").default,
  coinbaseicon: require("./Assets/coinbaseicon.svg").default,
  copy: require("./Assets/copy.svg").default,
  down: require("./Assets/down.svg").default,
  downroute: require("./Assets/downroute.svg").default,
  edit: require("./Assets/edit.svg").default,
  failedimg: require("./Assets/failedimg.svg").default,
  filter: require("./Assets/filter.svg").default,
  gas: require("./Assets/gas.svg").default,
  greentick: require("./Assets/greentick.svg").default,
  handstep: require("./Assets/handstep.svg").default,
  history: require("./Assets/history.svg").default,
  info: require("./Assets/info.svg").default,
  injectedicon: require("./Assets/injectedicon.svg").default,
  metamaskicon: require("./Assets/metamaskicon.svg").default,
  refresh: require("./Assets/refresh.svg").default,
  reverse: require("./Assets/reverse.svg").default,
  routeicon: require("./Assets/routeicon.svg").default,
  search: require("./Assets/search.svg").default,
  step1: require("./Assets/step1.svg").default,
  step2: require("./Assets/step2.svg").default,
  stepstick: require("./Assets/stepstick.svg").default,
  success: require("./Assets/success.png").default,
  tick: require("./Assets/tick.png").default,
  time: require("./Assets/time.svg").default,
  walletconnection: require("./Assets/walletconnecticon.svg").default,
};

export default images;
